results_dir: /opt/fauna/data/test_imgs/out/
dataset:
  infer_data_sources:
    image_dir: 
      - /opt/fauna/data/test_imgs
    captions: ["wallet", "keys", "ignore everything else"]
  batch_size: 1
  workers: 8
inference:
  trt_engine: "/opt/fauna/cache/online_mapping/grounding_dino.engine"
  conf_threshold: 0.1
  input_width: 960
  input_height: 544
  color_map:
    "keys": red
    "wallet": blue
    "people": yellow
model:
  backbone: swin_tiny_224_1k
  num_feature_levels: 4
  dec_layers: 6
  enc_layers: 6
  num_queries: 900
  dropout_ratio: 0.0
  dim_feedforward: 2048
